// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 主键ID
	GuidesID  int32     `gorm:"column:guides_id;not null" json:"guides_id"`                               // 攻略id
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`                                   // 用户id
	Context   string    `gorm:"column:context" json:"context"`                                            // 评论内容
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`   // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:1970-01-01 08:00:01" json:"updated_at"` // 更新时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
