// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExp = "exps"

// Exp mapped from table <exps>
type Exp struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键ID
	UserID    int     `gorm:"column:user_id;not null" json:"user_id"`                                 // 用户id
	Exp       int     `gorm:"column:exp;not null" json:"exp"`                                         // 经验数据
	Type      int     `gorm:"column:type;not null" json:"type"`                                       // 类型
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
}

// TableName Exp's table name
func (*Exp) TableName() string {
	return TableNameExp
}

func NewExp() *Exp {
	return &Exp{}
}

//etype：1是注册,2是收藏,3是换头像, 4是绑定钱包地址
//CreateExp 创建经验明细
func (m *Exp) CreateExp(userId, etype, exp int) (err error) {
	m.Type = etype
	m.UserID = userId
	m.Exp = exp
	err = db.Save(m).Error
	if err != nil {
		return
	}
	err = NewUser().ChangeUserExps(userId, exp)
	return
}
