// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFollow = "follows"

// Follow mapped from table <follows>
type Follow struct {
	UserID       int32     `gorm:"column:user_id;primaryKey" json:"user_id"`                                 // 用户id
	FollowUserID int32     `gorm:"column:follow_user_id;primaryKey" json:"follow_user_id"`                   // 关注用户id
	Status       int32     `gorm:"column:status;not null" json:"status"`                                     // 状态:0未关注,1已关注
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`   // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:1970-01-01 08:00:01" json:"updated_at"` // 更新时间
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
