// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGameUserPick = "game_user_picks"

// GameUserPick mapped from table <game_user_picks>
type GameUserPick struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键ID
	GameID   int32     `gorm:"column:game_id;not null" json:"game_id"`            // 游戏id
	UserID   int32     `gorm:"column:user_id;not null" json:"user_id"`            // 用户id
	PickTime time.Time `gorm:"column:pick_time;not null" json:"pick_time"`        // 打榜时间
}

// TableName GameUserPick's table name
func (*GameUserPick) TableName() string {
	return TableNameGameUserPick
}
