// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"ggslayer/utils"
	"math"
	"time"
)

const TableNameGameSocial = "game_socials"

// GameSocial mapped from table <game_socials>
type GameSocial struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键ID
	GameID          int32     `gorm:"column:game_id;not null" json:"game_id"`                                 // 游戏id
	SocialValue     int   	  `gorm:"column:social_value;not null" json:"social_value"`             // 游戏社交分值
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
}

// TableName GameSocial's table name
func (*GameSocial) TableName() string {
	return TableNameGameSocial
}

func NewGameSocial() *GameSocial {
	return &GameSocial{}
}

const (
	_insertGameSocialSql = "insert into game_socials(game_id,social_value,created_at) values "
)

//BatchInserch 批量插入
func (m *GameSocial) BatchInserch(gameSocials []*GameSocial) {
	db.Exec(m.GenInsertSQL(gameSocials))
}

// GenInsertSQL 生成批量插入的SQL
func (m *GameSocial) GenInsertSQL(gameSocials []*GameSocial) string {
	if len(gameSocials) == 0 {
		return ""
	}
	var (
		buf bytes.Buffer
		sql string
		now = time.Now().Local().Format(utils.TimeLayoutStr)
	)
	buf.WriteString(_insertGameSocialSql)
	for _, v := range gameSocials {
		s := fmt.Sprintf("(%d,%d,'%s'),", v.GameID, v.SocialValue, now)
		buf.WriteString(s)
	}
	sql = buf.String()
	return sql[0 : len(sql)-1]
}


//FindByGameId 根据条件查询游戏社交分
func (m *GameSocial) FindByGameId(gameId int32, b, d, n int) (socials []*GameSocial, err error) {
	startTime := ""
	endTime := ""
	if b == 1 {
		startTime = utils.DateFt(d, 2 * n)
		endTime = utils.DateFt(d, n)
	} else {
		startTime = utils.DateFt(d, n)
		endTime = time.Now().Format(utils.TimeLayoutStr)
	}
	err = db.Model(m).Where("game_id = ?", gameId).
		Where("created_at >= ? and created_at <= ?", startTime, endTime).
		Find(&socials).Error
	return
}

//CalcRate计算比例
func (m *GameSocial) CalcRateByGameId(gameId int32) (bmv7d, bmv1m int, rate7d, rate1m string) {
	bv7d := 0
	av7d := 0
	rate7d = ""
	//查询7天的game_social
	b7d, _ := m.FindByGameId(gameId, 0, 1, 7)
	a7d, _ := m.FindByGameId(gameId, 1, 1, 7)
	for _, b7 := range b7d {
		bv7d = bv7d + b7.SocialValue
	}
	for _, a7 := range a7d {
		av7d = av7d + a7.SocialValue
	}
	//计算7天社交分平均值
	bmv7d = int(math.Ceil(float64(bv7d) / float64(len(b7d))))
	if av7d == 0 {
		rate7d = "100"
	} else {
		amv7d := int(math.Ceil(float64(av7d) / float64(len(a7d))))
		rate := utils.Div((float64(bmv7d) - float64(amv7d)), float64(amv7d), 2)
		rate7d = fmt.Sprintf("%f", rate)
	}
	bv1m := 0
	av1m := 0
	rate1m = ""
	b1ms, _ := m.FindByGameId(gameId, 0, 2, 1)
	a1ms, _ := m.FindByGameId(gameId, 1, 2, 1)
	for _, b1m := range b1ms {
		bv1m = bv1m + b1m.SocialValue
	}
	for _, a1m := range a1ms {
		av1m = av1m + a1m.SocialValue
	}
	//计算30天社交分平均值
	bmv1m = int(math.Ceil(float64(bv1m) / float64(len(b1ms))))
	if av1m == 0 {
		rate1m = "100"
	} else {
		amv1m := int(math.Ceil(float64(av1m) / float64(len(a1ms))))
		rate := utils.Div((float64(bmv1m) - float64(amv1m)), float64(amv1m), 2)
		rate1m = fmt.Sprintf("%f", rate)
	}
	return
}
