// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePoint = "points"

// Point mapped from table <points>
type Point struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键ID
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`                                 // 用户id
	Point     int32     `gorm:"column:point;not null" json:"point"`                                     // 积分数据
	Type      int32     `gorm:"column:type;not null" json:"type"`                                       // 类型
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
}

// TableName Point's table name
func (*Point) TableName() string {
	return TableNamePoint
}
