// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserToken = "user_tokens"

// UserToken mapped from table <user_tokens>
type UserToken struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键ID
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`                                 // 用户id
	TokenType int       `gorm:"column:token_type;not null" json:"token_type"`                           // token类型
	Address   string    `gorm:"column:address;not null" json:"address"`                                 // token地址
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
}

func NewUserToken() *UserToken {
	return &UserToken{}
}

// TableName UserToken's table name
func (*UserToken) TableName() string {
	return TableNameUserToken
}

func (m *UserToken) Create() error {
	return db.Save(m).Error
}

//查看绑定地址
func (m *UserToken) FindAddress(userId, tokenType int, address string) (userToken *UserToken) {
	db.Model(m).Where("user_id = ? and token_type = ? and address = ?", userId, tokenType, address).Find(&userToken)
	return
}

//根据用户id查找钱包地址
func (m *UserToken) FindTokenByUserId(userId int) (userTokens []*UserToken, err error) {
	err = db.Model(m).Where("user_id = ?", userId).Find(&userTokens).Error
	return
}
